// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pftpziyewdkrwxffwgyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmdHB6aXlld2Rrcnd4ZmZ3Z3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NDg2MDIsImV4cCI6MjA2NDIyNDYwMn0.RClgFrrKtjKRZwd3SvJpMdp3PcE0mf18clPbsqdA9wQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
